# Build stage
FROM golang:1.26-alpine AS builder

WORKDIR /app


COPY go.mod go.sum ./
RUN go mod download


COPY ./cmd ./cmd   
COPY ./internal ./internal  

# Build the application for a Linux environment
RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/app/main.go

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

RUN adduser -D appuser

WORKDIR /home/appuser

COPY --from=builder /app/app .

USER appuser

EXPOSE 8080

ENTRYPOINT ["./app"]